remote_theme: pages-themes/time-machine@v0.2.0
title: "Stephanie McClurkin"
description: "CS-499 SNHU | Jan-Mar 2025 Computer Science Capstone Project"
github:
  repository_url: "https://github.com/smcclurkin0312/CS499weighttrackingapp"
show_downloads: false
